

[2017-09-29 09:35:28,533]  9 -- DEBUG -- Debuglog [Debug] -- 类名:[QuartzLogProvider]; 方法:[<GetLogger>b__5_0];
[9:35:28] [Error] Job UnUsedAttachment.DeleteAttachment threw an unhandled Exception:  

System.InvalidOperationException: 超时时间已到。超时时间已到，但是尚未从池中获取连接。出现这种情况可能是因为所有池连接均在使用，并且达到了最大池大小。
   在 System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   在 System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.Open()
   在 FileService.DataAccess.RepositoryBase.Db[T](Func`2 func) 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.DataAccess\RepositoryBase.cs:行号 16
   在 FileService.DataAccess.AttachmentDa.GetDeleteAttachments() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.DataAccess\AttachmentDa.cs:行号 24
   在 FileService.Biz.AttachmentBiz.DeleteAttachment() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.Biz\AttachmentBiz.cs:行号 20
   在 FileService.WebApi.Jobs.DeleteAttachmentJob.<>c.<Execute>b__1_0() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.WebApi\Jobs\DeleteAttachmentJob.cs:行号 18
   在 System.Threading.Tasks.Task.Execute()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   在 FileService.WebApi.Jobs.DeleteAttachmentJob.<Execute>d__1.MoveNext() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.WebApi\Jobs\DeleteAttachmentJob.cs:行号 15
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Quartz.Core.JobRunShell.<Run>d__9.MoveNext()


[2017-09-29 09:35:29,376]  15 -- DEBUG -- Debuglog [Debug] -- 类名:[QuartzLogProvider]; 方法:[<GetLogger>b__5_0];
[9:35:29] [Error] Job UnUsedAttachment.DeleteAttachment threw an unhandled Exception:  

System.Data.SqlClient.SqlException (0x80131904): 在从服务器接收结果时发生传输级错误。 (provider: TCP Provider, error: 0 - 信号灯超时时间已到) ---> System.ComponentModel.Win32Exception (0x80004005): 信号灯超时时间已到
   在 System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   在 System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   在 System.Data.SqlClient.TdsParserStateObject.ReadSniError(TdsParserStateObject stateObj, UInt32 error)
   在 System.Data.SqlClient.TdsParserStateObject.ReadSniSyncOverAsync()
   在 System.Data.SqlClient.TdsParserStateObject.TryReadNetworkPacket()
   在 System.Data.SqlClient.TdsParserStateObject.TryPrepareBuffer()
   在 System.Data.SqlClient.TdsParserStateObject.TryReadByte(Byte& value)
   在 System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   在 System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   在 System.Data.SqlClient.SqlDataReader.get_MetaData()
   在 System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption)
   在 System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   在 System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   在 System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   在 System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   在 Dapper.SqlMapper.ExecuteReaderWithFlagsFallback(IDbCommand cmd, Boolean wasClosed, CommandBehavior behavior)
   在 Dapper.SqlMapper.<QueryImpl>d__136`1.MoveNext()
   在 System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   在 System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   在 Dapper.SqlMapper.Query[T](IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Boolean buffered, Nullable`1 commandTimeout, Nullable`1 commandType)
   在 FileService.DataAccess.AttachmentDa.<>c.<GetDeleteAttachments>b__1_0(IDbConnection p) 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.DataAccess\AttachmentDa.cs:行号 24
   在 FileService.DataAccess.RepositoryBase.Db[T](Func`2 func) 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.DataAccess\RepositoryBase.cs:行号 17
   在 FileService.DataAccess.AttachmentDa.GetDeleteAttachments() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.DataAccess\AttachmentDa.cs:行号 24
   在 FileService.Biz.AttachmentBiz.DeleteAttachment() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.Biz\AttachmentBiz.cs:行号 20
   在 FileService.WebApi.Jobs.DeleteAttachmentJob.<>c.<Execute>b__1_0() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.WebApi\Jobs\DeleteAttachmentJob.cs:行号 18
   在 System.Threading.Tasks.Task.Execute()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   在 FileService.WebApi.Jobs.DeleteAttachmentJob.<Execute>d__1.MoveNext() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.WebApi\Jobs\DeleteAttachmentJob.cs:行号 15
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Quartz.Core.JobRunShell.<Run>d__9.MoveNext()
ClientConnectionId:3bdcddbd-04f8-478f-ab5b-e8fcc8f178ee
Error Number:121,State:0,Class:20


[2017-09-29 09:35:29,423]  15 -- DEBUG -- Debuglog [Debug] -- 类名:[QuartzLogProvider]; 方法:[<GetLogger>b__5_0];
[9:35:29] [Error] Job UnUsedAttachment.DeleteAttachment threw an exception. 

Quartz.SchedulerException: Job threw an unhandled exception. ---> System.Data.SqlClient.SqlException: 在从服务器接收结果时发生传输级错误。 (provider: TCP Provider, error: 0 - 信号灯超时时间已到) ---> System.ComponentModel.Win32Exception: 信号灯超时时间已到
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   在 System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   在 System.Data.SqlClient.TdsParserStateObject.ReadSniError(TdsParserStateObject stateObj, UInt32 error)
   在 System.Data.SqlClient.TdsParserStateObject.ReadSniSyncOverAsync()
   在 System.Data.SqlClient.TdsParserStateObject.TryReadNetworkPacket()
   在 System.Data.SqlClient.TdsParserStateObject.TryPrepareBuffer()
   在 System.Data.SqlClient.TdsParserStateObject.TryReadByte(Byte& value)
   在 System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   在 System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   在 System.Data.SqlClient.SqlDataReader.get_MetaData()
   在 System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption)
   在 System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   在 System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   在 System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   在 System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   在 Dapper.SqlMapper.ExecuteReaderWithFlagsFallback(IDbCommand cmd, Boolean wasClosed, CommandBehavior behavior)
   在 Dapper.SqlMapper.<QueryImpl>d__136`1.MoveNext()
   在 System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   在 System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   在 Dapper.SqlMapper.Query[T](IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Boolean buffered, Nullable`1 commandTimeout, Nullable`1 commandType)
   在 FileService.DataAccess.AttachmentDa.<>c.<GetDeleteAttachments>b__1_0(IDbConnection p) 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.DataAccess\AttachmentDa.cs:行号 24
   在 FileService.DataAccess.RepositoryBase.Db[T](Func`2 func) 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.DataAccess\RepositoryBase.cs:行号 17
   在 FileService.DataAccess.AttachmentDa.GetDeleteAttachments() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.DataAccess\AttachmentDa.cs:行号 24
   在 FileService.Biz.AttachmentBiz.DeleteAttachment() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.Biz\AttachmentBiz.cs:行号 20
   在 FileService.WebApi.Jobs.DeleteAttachmentJob.<>c.<Execute>b__1_0() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.WebApi\Jobs\DeleteAttachmentJob.cs:行号 18
   在 System.Threading.Tasks.Task.Execute()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   在 FileService.WebApi.Jobs.DeleteAttachmentJob.<Execute>d__1.MoveNext() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.WebApi\Jobs\DeleteAttachmentJob.cs:行号 15
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Quartz.Core.JobRunShell.<Run>d__9.MoveNext()
   --- 内部异常堆栈跟踪的结尾 --- [See nested exception: System.Data.SqlClient.SqlException (0x80131904): 在从服务器接收结果时发生传输级错误。 (provider: TCP Provider, error: 0 - 信号灯超时时间已到) ---> System.ComponentModel.Win32Exception (0x80004005): 信号灯超时时间已到
   在 System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   在 System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   在 System.Data.SqlClient.TdsParserStateObject.ReadSniError(TdsParserStateObject stateObj, UInt32 error)
   在 System.Data.SqlClient.TdsParserStateObject.ReadSniSyncOverAsync()
   在 System.Data.SqlClient.TdsParserStateObject.TryReadNetworkPacket()
   在 System.Data.SqlClient.TdsParserStateObject.TryPrepareBuffer()
   在 System.Data.SqlClient.TdsParserStateObject.TryReadByte(Byte& value)
   在 System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   在 System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   在 System.Data.SqlClient.SqlDataReader.get_MetaData()
   在 System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption)
   在 System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   在 System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   在 System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   在 System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   在 Dapper.SqlMapper.ExecuteReaderWithFlagsFallback(IDbCommand cmd, Boolean wasClosed, CommandBehavior behavior)
   在 Dapper.SqlMapper.<QueryImpl>d__136`1.MoveNext()
   在 System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   在 System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   在 Dapper.SqlMapper.Query[T](IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Boolean buffered, Nullable`1 commandTimeout, Nullable`1 commandType)
   在 FileService.DataAccess.AttachmentDa.<>c.<GetDeleteAttachments>b__1_0(IDbConnection p) 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.DataAccess\AttachmentDa.cs:行号 24
   在 FileService.DataAccess.RepositoryBase.Db[T](Func`2 func) 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.DataAccess\RepositoryBase.cs:行号 17
   在 FileService.DataAccess.AttachmentDa.GetDeleteAttachments() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.DataAccess\AttachmentDa.cs:行号 24
   在 FileService.Biz.AttachmentBiz.DeleteAttachment() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.Biz\AttachmentBiz.cs:行号 20
   在 FileService.WebApi.Jobs.DeleteAttachmentJob.<>c.<Execute>b__1_0() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.WebApi\Jobs\DeleteAttachmentJob.cs:行号 18
   在 System.Threading.Tasks.Task.Execute()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   在 FileService.WebApi.Jobs.DeleteAttachmentJob.<Execute>d__1.MoveNext() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.WebApi\Jobs\DeleteAttachmentJob.cs:行号 15
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Quartz.Core.JobRunShell.<Run>d__9.MoveNext()
ClientConnectionId:3bdcddbd-04f8-478f-ab5b-e8fcc8f178ee
Error Number:121,State:0,Class:20]


[2017-09-29 09:35:29,407]  9 -- DEBUG -- Debuglog [Debug] -- 类名:[QuartzLogProvider]; 方法:[<GetLogger>b__5_0];
[9:35:29] [Error] Job UnUsedAttachment.DeleteAttachment threw an exception. 

Quartz.SchedulerException: Job threw an unhandled exception. ---> System.InvalidOperationException: 超时时间已到。超时时间已到，但是尚未从池中获取连接。出现这种情况可能是因为所有池连接均在使用，并且达到了最大池大小。
   在 System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   在 System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.Open()
   在 FileService.DataAccess.RepositoryBase.Db[T](Func`2 func) 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.DataAccess\RepositoryBase.cs:行号 16
   在 FileService.DataAccess.AttachmentDa.GetDeleteAttachments() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.DataAccess\AttachmentDa.cs:行号 24
   在 FileService.Biz.AttachmentBiz.DeleteAttachment() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.Biz\AttachmentBiz.cs:行号 20
   在 FileService.WebApi.Jobs.DeleteAttachmentJob.<>c.<Execute>b__1_0() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.WebApi\Jobs\DeleteAttachmentJob.cs:行号 18
   在 System.Threading.Tasks.Task.Execute()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   在 FileService.WebApi.Jobs.DeleteAttachmentJob.<Execute>d__1.MoveNext() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.WebApi\Jobs\DeleteAttachmentJob.cs:行号 15
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Quartz.Core.JobRunShell.<Run>d__9.MoveNext()
   --- 内部异常堆栈跟踪的结尾 --- [See nested exception: System.InvalidOperationException: 超时时间已到。超时时间已到，但是尚未从池中获取连接。出现这种情况可能是因为所有池连接均在使用，并且达到了最大池大小。
   在 System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   在 System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.Open()
   在 FileService.DataAccess.RepositoryBase.Db[T](Func`2 func) 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.DataAccess\RepositoryBase.cs:行号 16
   在 FileService.DataAccess.AttachmentDa.GetDeleteAttachments() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.DataAccess\AttachmentDa.cs:行号 24
   在 FileService.Biz.AttachmentBiz.DeleteAttachment() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.Biz\AttachmentBiz.cs:行号 20
   在 FileService.WebApi.Jobs.DeleteAttachmentJob.<>c.<Execute>b__1_0() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.WebApi\Jobs\DeleteAttachmentJob.cs:行号 18
   在 System.Threading.Tasks.Task.Execute()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   在 FileService.WebApi.Jobs.DeleteAttachmentJob.<Execute>d__1.MoveNext() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.WebApi\Jobs\DeleteAttachmentJob.cs:行号 15
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Quartz.Core.JobRunShell.<Run>d__9.MoveNext()]


[2017-09-29 09:36:15,876]  7 -- DEBUG -- Debuglog [Debug] -- 类名:[QuartzLogProvider]; 方法:[<GetLogger>b__5_0];
[9:36:15] [Error] Job UnUsedAttachment.DeleteAttachment threw an unhandled Exception:  

System.InvalidOperationException: 超时时间已到。超时时间已到，但是尚未从池中获取连接。出现这种情况可能是因为所有池连接均在使用，并且达到了最大池大小。
   在 System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   在 System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.Open()
   在 FileService.DataAccess.RepositoryBase.Db[T](Func`2 func) 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.DataAccess\RepositoryBase.cs:行号 16
   在 FileService.DataAccess.AttachmentDa.GetDeleteAttachments() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.DataAccess\AttachmentDa.cs:行号 24
   在 FileService.Biz.AttachmentBiz.DeleteAttachment() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.Biz\AttachmentBiz.cs:行号 20
   在 FileService.WebApi.Jobs.DeleteAttachmentJob.<>c.<Execute>b__1_0() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.WebApi\Jobs\DeleteAttachmentJob.cs:行号 18
   在 System.Threading.Tasks.Task.Execute()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   在 FileService.WebApi.Jobs.DeleteAttachmentJob.<Execute>d__1.MoveNext() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.WebApi\Jobs\DeleteAttachmentJob.cs:行号 15
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Quartz.Core.JobRunShell.<Run>d__9.MoveNext()


[2017-09-29 09:36:15,928]  9 -- DEBUG -- Debuglog [Debug] -- 类名:[QuartzLogProvider]; 方法:[<GetLogger>b__5_0];
[9:36:15] [Error] Job UnUsedAttachment.DeleteAttachment threw an unhandled Exception:  

System.InvalidOperationException: 超时时间已到。超时时间已到，但是尚未从池中获取连接。出现这种情况可能是因为所有池连接均在使用，并且达到了最大池大小。
   在 System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   在 System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.Open()
   在 FileService.DataAccess.RepositoryBase.Db[T](Func`2 func) 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.DataAccess\RepositoryBase.cs:行号 16
   在 FileService.DataAccess.AttachmentDa.GetDeleteAttachments() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.DataAccess\AttachmentDa.cs:行号 24
   在 FileService.Biz.AttachmentBiz.DeleteAttachment() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.Biz\AttachmentBiz.cs:行号 20
   在 FileService.WebApi.Jobs.DeleteAttachmentJob.<>c.<Execute>b__1_0() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.WebApi\Jobs\DeleteAttachmentJob.cs:行号 18
   在 System.Threading.Tasks.Task.Execute()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   在 FileService.WebApi.Jobs.DeleteAttachmentJob.<Execute>d__1.MoveNext() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.WebApi\Jobs\DeleteAttachmentJob.cs:行号 15
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Quartz.Core.JobRunShell.<Run>d__9.MoveNext()


[2017-09-29 09:36:15,928]  7 -- DEBUG -- Debuglog [Debug] -- 类名:[QuartzLogProvider]; 方法:[<GetLogger>b__5_0];
[9:36:15] [Error] Job UnUsedAttachment.DeleteAttachment threw an exception. 

Quartz.SchedulerException: Job threw an unhandled exception. ---> System.InvalidOperationException: 超时时间已到。超时时间已到，但是尚未从池中获取连接。出现这种情况可能是因为所有池连接均在使用，并且达到了最大池大小。
   在 System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   在 System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.Open()
   在 FileService.DataAccess.RepositoryBase.Db[T](Func`2 func) 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.DataAccess\RepositoryBase.cs:行号 16
   在 FileService.DataAccess.AttachmentDa.GetDeleteAttachments() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.DataAccess\AttachmentDa.cs:行号 24
   在 FileService.Biz.AttachmentBiz.DeleteAttachment() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.Biz\AttachmentBiz.cs:行号 20
   在 FileService.WebApi.Jobs.DeleteAttachmentJob.<>c.<Execute>b__1_0() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.WebApi\Jobs\DeleteAttachmentJob.cs:行号 18
   在 System.Threading.Tasks.Task.Execute()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   在 FileService.WebApi.Jobs.DeleteAttachmentJob.<Execute>d__1.MoveNext() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.WebApi\Jobs\DeleteAttachmentJob.cs:行号 15
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Quartz.Core.JobRunShell.<Run>d__9.MoveNext()
   --- 内部异常堆栈跟踪的结尾 --- [See nested exception: System.InvalidOperationException: 超时时间已到。超时时间已到，但是尚未从池中获取连接。出现这种情况可能是因为所有池连接均在使用，并且达到了最大池大小。
   在 System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   在 System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.Open()
   在 FileService.DataAccess.RepositoryBase.Db[T](Func`2 func) 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.DataAccess\RepositoryBase.cs:行号 16
   在 FileService.DataAccess.AttachmentDa.GetDeleteAttachments() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.DataAccess\AttachmentDa.cs:行号 24
   在 FileService.Biz.AttachmentBiz.DeleteAttachment() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.Biz\AttachmentBiz.cs:行号 20
   在 FileService.WebApi.Jobs.DeleteAttachmentJob.<>c.<Execute>b__1_0() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.WebApi\Jobs\DeleteAttachmentJob.cs:行号 18
   在 System.Threading.Tasks.Task.Execute()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   在 FileService.WebApi.Jobs.DeleteAttachmentJob.<Execute>d__1.MoveNext() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.WebApi\Jobs\DeleteAttachmentJob.cs:行号 15
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Quartz.Core.JobRunShell.<Run>d__9.MoveNext()]


[2017-09-29 09:36:16,343]  8 -- DEBUG -- Debuglog [Debug] -- 类名:[QuartzLogProvider]; 方法:[<GetLogger>b__5_0];
[9:36:16] [Error] Job UnUsedAttachment.DeleteAttachment threw an unhandled Exception:  

System.InvalidOperationException: 超时时间已到。超时时间已到，但是尚未从池中获取连接。出现这种情况可能是因为所有池连接均在使用，并且达到了最大池大小。
   在 System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   在 System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.Open()
   在 FileService.DataAccess.RepositoryBase.Db[T](Func`2 func) 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.DataAccess\RepositoryBase.cs:行号 16
   在 FileService.DataAccess.AttachmentDa.GetDeleteAttachments() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.DataAccess\AttachmentDa.cs:行号 24
   在 FileService.Biz.AttachmentBiz.DeleteAttachment() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.Biz\AttachmentBiz.cs:行号 20
   在 FileService.WebApi.Jobs.DeleteAttachmentJob.<>c.<Execute>b__1_0() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.WebApi\Jobs\DeleteAttachmentJob.cs:行号 18
   在 System.Threading.Tasks.Task.Execute()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   在 FileService.WebApi.Jobs.DeleteAttachmentJob.<Execute>d__1.MoveNext() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.WebApi\Jobs\DeleteAttachmentJob.cs:行号 15
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Quartz.Core.JobRunShell.<Run>d__9.MoveNext()


[2017-09-29 09:36:16,343]  9 -- DEBUG -- Debuglog [Debug] -- 类名:[QuartzLogProvider]; 方法:[<GetLogger>b__5_0];
[9:36:16] [Error] Job UnUsedAttachment.DeleteAttachment threw an exception. 

Quartz.SchedulerException: Job threw an unhandled exception. ---> System.InvalidOperationException: 超时时间已到。超时时间已到，但是尚未从池中获取连接。出现这种情况可能是因为所有池连接均在使用，并且达到了最大池大小。
   在 System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   在 System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.Open()
   在 FileService.DataAccess.RepositoryBase.Db[T](Func`2 func) 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.DataAccess\RepositoryBase.cs:行号 16
   在 FileService.DataAccess.AttachmentDa.GetDeleteAttachments() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.DataAccess\AttachmentDa.cs:行号 24
   在 FileService.Biz.AttachmentBiz.DeleteAttachment() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.Biz\AttachmentBiz.cs:行号 20
   在 FileService.WebApi.Jobs.DeleteAttachmentJob.<>c.<Execute>b__1_0() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.WebApi\Jobs\DeleteAttachmentJob.cs:行号 18
   在 System.Threading.Tasks.Task.Execute()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   在 FileService.WebApi.Jobs.DeleteAttachmentJob.<Execute>d__1.MoveNext() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.WebApi\Jobs\DeleteAttachmentJob.cs:行号 15
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Quartz.Core.JobRunShell.<Run>d__9.MoveNext()
   --- 内部异常堆栈跟踪的结尾 --- [See nested exception: System.InvalidOperationException: 超时时间已到。超时时间已到，但是尚未从池中获取连接。出现这种情况可能是因为所有池连接均在使用，并且达到了最大池大小。
   在 System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   在 System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.Open()
   在 FileService.DataAccess.RepositoryBase.Db[T](Func`2 func) 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.DataAccess\RepositoryBase.cs:行号 16
   在 FileService.DataAccess.AttachmentDa.GetDeleteAttachments() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.DataAccess\AttachmentDa.cs:行号 24
   在 FileService.Biz.AttachmentBiz.DeleteAttachment() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.Biz\AttachmentBiz.cs:行号 20
   在 FileService.WebApi.Jobs.DeleteAttachmentJob.<>c.<Execute>b__1_0() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.WebApi\Jobs\DeleteAttachmentJob.cs:行号 18
   在 System.Threading.Tasks.Task.Execute()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   在 FileService.WebApi.Jobs.DeleteAttachmentJob.<Execute>d__1.MoveNext() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.WebApi\Jobs\DeleteAttachmentJob.cs:行号 15
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Quartz.Core.JobRunShell.<Run>d__9.MoveNext()]


[2017-09-29 09:36:17,171]  10 -- DEBUG -- Debuglog [Debug] -- 类名:[QuartzLogProvider]; 方法:[<GetLogger>b__5_0];
[9:36:17] [Error] Job UnUsedAttachment.DeleteAttachment threw an unhandled Exception:  

System.Data.SqlClient.SqlException (0x80131904): 在与 SQL Server 建立连接时出现与网络相关的或特定于实例的错误。未找到或无法访问服务器。请验证实例名称是否正确并且 SQL Server 已配置为允许远程连接。 (provider: Named Pipes Provider, error: 40 - 无法打开到 SQL Server 的连接) ---> System.ComponentModel.Win32Exception (0x80004005): 找不到网络路径。
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   在 System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.Open()
   在 FileService.DataAccess.RepositoryBase.Db[T](Func`2 func) 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.DataAccess\RepositoryBase.cs:行号 16
   在 FileService.DataAccess.AttachmentDa.GetDeleteAttachments() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.DataAccess\AttachmentDa.cs:行号 24
   在 FileService.Biz.AttachmentBiz.DeleteAttachment() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.Biz\AttachmentBiz.cs:行号 20
   在 FileService.WebApi.Jobs.DeleteAttachmentJob.<>c.<Execute>b__1_0() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.WebApi\Jobs\DeleteAttachmentJob.cs:行号 18
   在 System.Threading.Tasks.Task.Execute()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   在 FileService.WebApi.Jobs.DeleteAttachmentJob.<Execute>d__1.MoveNext() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.WebApi\Jobs\DeleteAttachmentJob.cs:行号 15
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Quartz.Core.JobRunShell.<Run>d__9.MoveNext()
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:53,State:0,Class:20


[2017-09-29 09:36:16,343]  11 -- DEBUG -- Debuglog [Debug] -- 类名:[QuartzLogProvider]; 方法:[<GetLogger>b__5_0];
[9:36:16] [Error] Job UnUsedAttachment.DeleteAttachment threw an unhandled Exception:  

System.InvalidOperationException: 超时时间已到。超时时间已到，但是尚未从池中获取连接。出现这种情况可能是因为所有池连接均在使用，并且达到了最大池大小。
   在 System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   在 System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.Open()
   在 FileService.DataAccess.RepositoryBase.Db[T](Func`2 func) 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.DataAccess\RepositoryBase.cs:行号 16
   在 FileService.DataAccess.AttachmentDa.GetDeleteAttachments() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.DataAccess\AttachmentDa.cs:行号 24
   在 FileService.Biz.AttachmentBiz.DeleteAttachment() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.Biz\AttachmentBiz.cs:行号 20
   在 FileService.WebApi.Jobs.DeleteAttachmentJob.<>c.<Execute>b__1_0() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.WebApi\Jobs\DeleteAttachmentJob.cs:行号 18
   在 System.Threading.Tasks.Task.Execute()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   在 FileService.WebApi.Jobs.DeleteAttachmentJob.<Execute>d__1.MoveNext() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.WebApi\Jobs\DeleteAttachmentJob.cs:行号 15
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Quartz.Core.JobRunShell.<Run>d__9.MoveNext()


[2017-09-29 09:36:17,078]  15 -- DEBUG -- Debuglog [Debug] -- 类名:[QuartzLogProvider]; 方法:[<GetLogger>b__5_0];
[9:36:16] [Error] Job UnUsedAttachment.DeleteAttachment threw an unhandled Exception:  

System.InvalidOperationException: 超时时间已到。超时时间已到，但是尚未从池中获取连接。出现这种情况可能是因为所有池连接均在使用，并且达到了最大池大小。
   在 System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   在 System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.Open()
   在 FileService.DataAccess.RepositoryBase.Db[T](Func`2 func) 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.DataAccess\RepositoryBase.cs:行号 16
   在 FileService.DataAccess.AttachmentDa.GetDeleteAttachments() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.DataAccess\AttachmentDa.cs:行号 24
   在 FileService.Biz.AttachmentBiz.DeleteAttachment() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.Biz\AttachmentBiz.cs:行号 20
   在 FileService.WebApi.Jobs.DeleteAttachmentJob.<>c.<Execute>b__1_0() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.WebApi\Jobs\DeleteAttachmentJob.cs:行号 18
   在 System.Threading.Tasks.Task.Execute()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   在 FileService.WebApi.Jobs.DeleteAttachmentJob.<Execute>d__1.MoveNext() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.WebApi\Jobs\DeleteAttachmentJob.cs:行号 15
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Quartz.Core.JobRunShell.<Run>d__9.MoveNext()


[2017-09-29 09:36:18,739]  9 -- DEBUG -- Debuglog [Debug] -- 类名:[QuartzLogProvider]; 方法:[<GetLogger>b__5_0];
[9:36:18] [Error] Job UnUsedAttachment.DeleteAttachment threw an unhandled Exception:  

System.Data.SqlClient.SqlException (0x80131904): 在与 SQL Server 建立连接时出现与网络相关的或特定于实例的错误。未找到或无法访问服务器。请验证实例名称是否正确并且 SQL Server 已配置为允许远程连接。 (provider: Named Pipes Provider, error: 40 - 无法打开到 SQL Server 的连接) ---> System.ComponentModel.Win32Exception (0x80004005): 找不到网络路径。
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   在 System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.Open()
   在 FileService.DataAccess.RepositoryBase.Db[T](Func`2 func) 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.DataAccess\RepositoryBase.cs:行号 16
   在 FileService.DataAccess.AttachmentDa.GetDeleteAttachments() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.DataAccess\AttachmentDa.cs:行号 24
   在 FileService.Biz.AttachmentBiz.DeleteAttachment() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.Biz\AttachmentBiz.cs:行号 20
   在 FileService.WebApi.Jobs.DeleteAttachmentJob.<>c.<Execute>b__1_0() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.WebApi\Jobs\DeleteAttachmentJob.cs:行号 18
   在 System.Threading.Tasks.Task.Execute()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   在 FileService.WebApi.Jobs.DeleteAttachmentJob.<Execute>d__1.MoveNext() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.WebApi\Jobs\DeleteAttachmentJob.cs:行号 15
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Quartz.Core.JobRunShell.<Run>d__9.MoveNext()
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:53,State:0,Class:20


[2017-09-29 09:36:18,739]  9 -- DEBUG -- Debuglog [Debug] -- 类名:[QuartzLogProvider]; 方法:[<GetLogger>b__5_0];
[9:36:18] [Error] Job UnUsedAttachment.DeleteAttachment threw an exception. 

Quartz.SchedulerException: Job threw an unhandled exception. ---> System.Data.SqlClient.SqlException: 在与 SQL Server 建立连接时出现与网络相关的或特定于实例的错误。未找到或无法访问服务器。请验证实例名称是否正确并且 SQL Server 已配置为允许远程连接。 (provider: Named Pipes Provider, error: 40 - 无法打开到 SQL Server 的连接) ---> System.ComponentModel.Win32Exception: 找不到网络路径。
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   在 System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.Open()
   在 FileService.DataAccess.RepositoryBase.Db[T](Func`2 func) 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.DataAccess\RepositoryBase.cs:行号 16
   在 FileService.DataAccess.AttachmentDa.GetDeleteAttachments() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.DataAccess\AttachmentDa.cs:行号 24
   在 FileService.Biz.AttachmentBiz.DeleteAttachment() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.Biz\AttachmentBiz.cs:行号 20
   在 FileService.WebApi.Jobs.DeleteAttachmentJob.<>c.<Execute>b__1_0() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.WebApi\Jobs\DeleteAttachmentJob.cs:行号 18
   在 System.Threading.Tasks.Task.Execute()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   在 FileService.WebApi.Jobs.DeleteAttachmentJob.<Execute>d__1.MoveNext() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.WebApi\Jobs\DeleteAttachmentJob.cs:行号 15
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Quartz.Core.JobRunShell.<Run>d__9.MoveNext()
   --- 内部异常堆栈跟踪的结尾 --- [See nested exception: System.Data.SqlClient.SqlException (0x80131904): 在与 SQL Server 建立连接时出现与网络相关的或特定于实例的错误。未找到或无法访问服务器。请验证实例名称是否正确并且 SQL Server 已配置为允许远程连接。 (provider: Named Pipes Provider, error: 40 - 无法打开到 SQL Server 的连接) ---> System.ComponentModel.Win32Exception (0x80004005): 找不到网络路径。
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   在 System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.Open()
   在 FileService.DataAccess.RepositoryBase.Db[T](Func`2 func) 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.DataAccess\RepositoryBase.cs:行号 16
   在 FileService.DataAccess.AttachmentDa.GetDeleteAttachments() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.DataAccess\AttachmentDa.cs:行号 24
   在 FileService.Biz.AttachmentBiz.DeleteAttachment() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.Biz\AttachmentBiz.cs:行号 20
   在 FileService.WebApi.Jobs.DeleteAttachmentJob.<>c.<Execute>b__1_0() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.WebApi\Jobs\DeleteAttachmentJob.cs:行号 18
   在 System.Threading.Tasks.Task.Execute()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   在 FileService.WebApi.Jobs.DeleteAttachmentJob.<Execute>d__1.MoveNext() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.WebApi\Jobs\DeleteAttachmentJob.cs:行号 15
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Quartz.Core.JobRunShell.<Run>d__9.MoveNext()
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:53,State:0,Class:20]


[2017-09-29 09:36:17,078]  8 -- DEBUG -- Debuglog [Debug] -- 类名:[QuartzLogProvider]; 方法:[<GetLogger>b__5_0];
[9:36:17] [Error] Job UnUsedAttachment.DeleteAttachment threw an exception. 

Quartz.SchedulerException: Job threw an unhandled exception. ---> System.InvalidOperationException: 超时时间已到。超时时间已到，但是尚未从池中获取连接。出现这种情况可能是因为所有池连接均在使用，并且达到了最大池大小。
   在 System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   在 System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.Open()
   在 FileService.DataAccess.RepositoryBase.Db[T](Func`2 func) 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.DataAccess\RepositoryBase.cs:行号 16
   在 FileService.DataAccess.AttachmentDa.GetDeleteAttachments() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.DataAccess\AttachmentDa.cs:行号 24
   在 FileService.Biz.AttachmentBiz.DeleteAttachment() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.Biz\AttachmentBiz.cs:行号 20
   在 FileService.WebApi.Jobs.DeleteAttachmentJob.<>c.<Execute>b__1_0() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.WebApi\Jobs\DeleteAttachmentJob.cs:行号 18
   在 System.Threading.Tasks.Task.Execute()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   在 FileService.WebApi.Jobs.DeleteAttachmentJob.<Execute>d__1.MoveNext() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.WebApi\Jobs\DeleteAttachmentJob.cs:行号 15
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Quartz.Core.JobRunShell.<Run>d__9.MoveNext()
   --- 内部异常堆栈跟踪的结尾 --- [See nested exception: System.InvalidOperationException: 超时时间已到。超时时间已到，但是尚未从池中获取连接。出现这种情况可能是因为所有池连接均在使用，并且达到了最大池大小。
   在 System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   在 System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.Open()
   在 FileService.DataAccess.RepositoryBase.Db[T](Func`2 func) 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.DataAccess\RepositoryBase.cs:行号 16
   在 FileService.DataAccess.AttachmentDa.GetDeleteAttachments() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.DataAccess\AttachmentDa.cs:行号 24
   在 FileService.Biz.AttachmentBiz.DeleteAttachment() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.Biz\AttachmentBiz.cs:行号 20
   在 FileService.WebApi.Jobs.DeleteAttachmentJob.<>c.<Execute>b__1_0() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.WebApi\Jobs\DeleteAttachmentJob.cs:行号 18
   在 System.Threading.Tasks.Task.Execute()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   在 FileService.WebApi.Jobs.DeleteAttachmentJob.<Execute>d__1.MoveNext() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.WebApi\Jobs\DeleteAttachmentJob.cs:行号 15
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Quartz.Core.JobRunShell.<Run>d__9.MoveNext()]


[2017-09-29 09:36:17,124]  6 -- DEBUG -- Debuglog [Debug] -- 类名:[QuartzLogProvider]; 方法:[<GetLogger>b__5_0];
[9:36:17] [Error] Job UnUsedAttachment.DeleteAttachment threw an unhandled Exception:  

System.Data.SqlClient.SqlException (0x80131904): 在与 SQL Server 建立连接时出现与网络相关的或特定于实例的错误。未找到或无法访问服务器。请验证实例名称是否正确并且 SQL Server 已配置为允许远程连接。 (provider: Named Pipes Provider, error: 40 - 无法打开到 SQL Server 的连接) ---> System.ComponentModel.Win32Exception (0x80004005): 找不到网络路径。
   在 System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling)
   在 System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   在 System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   在 System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   在 System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   在 System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.Open()
   在 FileService.DataAccess.RepositoryBase.Db[T](Func`2 func) 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.DataAccess\RepositoryBase.cs:行号 16
   在 FileService.DataAccess.AttachmentDa.GetDeleteAttachments() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.DataAccess\AttachmentDa.cs:行号 24
   在 FileService.Biz.AttachmentBiz.DeleteAttachment() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.Biz\AttachmentBiz.cs:行号 20
   在 FileService.WebApi.Jobs.DeleteAttachmentJob.<>c.<Execute>b__1_0() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.WebApi\Jobs\DeleteAttachmentJob.cs:行号 18
   在 System.Threading.Tasks.Task.Execute()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   在 FileService.WebApi.Jobs.DeleteAttachmentJob.<Execute>d__1.MoveNext() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.WebApi\Jobs\DeleteAttachmentJob.cs:行号 15
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Quartz.Core.JobRunShell.<Run>d__9.MoveNext()
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:53,State:0,Class:20


[2017-09-29 09:36:17,453]  10 -- DEBUG -- Debuglog [Debug] -- 类名:[QuartzLogProvider]; 方法:[<GetLogger>b__5_0];
[9:36:17] [Error] Job UnUsedAttachment.DeleteAttachment threw an exception. 

Quartz.SchedulerException: Job threw an unhandled exception. ---> System.Data.SqlClient.SqlException: 在与 SQL Server 建立连接时出现与网络相关的或特定于实例的错误。未找到或无法访问服务器。请验证实例名称是否正确并且 SQL Server 已配置为允许远程连接。 (provider: Named Pipes Provider, error: 40 - 无法打开到 SQL Server 的连接) ---> System.ComponentModel.Win32Exception: 找不到网络路径。
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   在 System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.Open()
   在 FileService.DataAccess.RepositoryBase.Db[T](Func`2 func) 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.DataAccess\RepositoryBase.cs:行号 16
   在 FileService.DataAccess.AttachmentDa.GetDeleteAttachments() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.DataAccess\AttachmentDa.cs:行号 24
   在 FileService.Biz.AttachmentBiz.DeleteAttachment() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.Biz\AttachmentBiz.cs:行号 20
   在 FileService.WebApi.Jobs.DeleteAttachmentJob.<>c.<Execute>b__1_0() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.WebApi\Jobs\DeleteAttachmentJob.cs:行号 18
   在 System.Threading.Tasks.Task.Execute()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   在 FileService.WebApi.Jobs.DeleteAttachmentJob.<Execute>d__1.MoveNext() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.WebApi\Jobs\DeleteAttachmentJob.cs:行号 15
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Quartz.Core.JobRunShell.<Run>d__9.MoveNext()
   --- 内部异常堆栈跟踪的结尾 --- [See nested exception: System.Data.SqlClient.SqlException (0x80131904): 在与 SQL Server 建立连接时出现与网络相关的或特定于实例的错误。未找到或无法访问服务器。请验证实例名称是否正确并且 SQL Server 已配置为允许远程连接。 (provider: Named Pipes Provider, error: 40 - 无法打开到 SQL Server 的连接) ---> System.ComponentModel.Win32Exception (0x80004005): 找不到网络路径。
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   在 System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.Open()
   在 FileService.DataAccess.RepositoryBase.Db[T](Func`2 func) 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.DataAccess\RepositoryBase.cs:行号 16
   在 FileService.DataAccess.AttachmentDa.GetDeleteAttachments() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.DataAccess\AttachmentDa.cs:行号 24
   在 FileService.Biz.AttachmentBiz.DeleteAttachment() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.Biz\AttachmentBiz.cs:行号 20
   在 FileService.WebApi.Jobs.DeleteAttachmentJob.<>c.<Execute>b__1_0() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.WebApi\Jobs\DeleteAttachmentJob.cs:行号 18
   在 System.Threading.Tasks.Task.Execute()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   在 FileService.WebApi.Jobs.DeleteAttachmentJob.<Execute>d__1.MoveNext() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.WebApi\Jobs\DeleteAttachmentJob.cs:行号 15
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Quartz.Core.JobRunShell.<Run>d__9.MoveNext()
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:53,State:0,Class:20]


[2017-09-29 09:36:18,676]  11 -- DEBUG -- Debuglog [Debug] -- 类名:[QuartzLogProvider]; 方法:[<GetLogger>b__5_0];
[9:36:18] [Error] Job UnUsedAttachment.DeleteAttachment threw an exception. 

Quartz.SchedulerException: Job threw an unhandled exception. ---> System.InvalidOperationException: 超时时间已到。超时时间已到，但是尚未从池中获取连接。出现这种情况可能是因为所有池连接均在使用，并且达到了最大池大小。
   在 System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   在 System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.Open()
   在 FileService.DataAccess.RepositoryBase.Db[T](Func`2 func) 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.DataAccess\RepositoryBase.cs:行号 16
   在 FileService.DataAccess.AttachmentDa.GetDeleteAttachments() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.DataAccess\AttachmentDa.cs:行号 24
   在 FileService.Biz.AttachmentBiz.DeleteAttachment() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.Biz\AttachmentBiz.cs:行号 20
   在 FileService.WebApi.Jobs.DeleteAttachmentJob.<>c.<Execute>b__1_0() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.WebApi\Jobs\DeleteAttachmentJob.cs:行号 18
   在 System.Threading.Tasks.Task.Execute()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   在 FileService.WebApi.Jobs.DeleteAttachmentJob.<Execute>d__1.MoveNext() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.WebApi\Jobs\DeleteAttachmentJob.cs:行号 15
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Quartz.Core.JobRunShell.<Run>d__9.MoveNext()
   --- 内部异常堆栈跟踪的结尾 --- [See nested exception: System.InvalidOperationException: 超时时间已到。超时时间已到，但是尚未从池中获取连接。出现这种情况可能是因为所有池连接均在使用，并且达到了最大池大小。
   在 System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   在 System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.Open()
   在 FileService.DataAccess.RepositoryBase.Db[T](Func`2 func) 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.DataAccess\RepositoryBase.cs:行号 16
   在 FileService.DataAccess.AttachmentDa.GetDeleteAttachments() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.DataAccess\AttachmentDa.cs:行号 24
   在 FileService.Biz.AttachmentBiz.DeleteAttachment() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.Biz\AttachmentBiz.cs:行号 20
   在 FileService.WebApi.Jobs.DeleteAttachmentJob.<>c.<Execute>b__1_0() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.WebApi\Jobs\DeleteAttachmentJob.cs:行号 18
   在 System.Threading.Tasks.Task.Execute()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   在 FileService.WebApi.Jobs.DeleteAttachmentJob.<Execute>d__1.MoveNext() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.WebApi\Jobs\DeleteAttachmentJob.cs:行号 15
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Quartz.Core.JobRunShell.<Run>d__9.MoveNext()]


[2017-09-29 09:36:22,046]  6 -- DEBUG -- Debuglog [Debug] -- 类名:[QuartzLogProvider]; 方法:[<GetLogger>b__5_0];
[9:36:22] [Error] Job UnUsedAttachment.DeleteAttachment threw an exception. 

Quartz.SchedulerException: Job threw an unhandled exception. ---> System.Data.SqlClient.SqlException: 在与 SQL Server 建立连接时出现与网络相关的或特定于实例的错误。未找到或无法访问服务器。请验证实例名称是否正确并且 SQL Server 已配置为允许远程连接。 (provider: Named Pipes Provider, error: 40 - 无法打开到 SQL Server 的连接) ---> System.ComponentModel.Win32Exception: 找不到网络路径。
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling)
   在 System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   在 System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   在 System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   在 System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   在 System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.Open()
   在 FileService.DataAccess.RepositoryBase.Db[T](Func`2 func) 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.DataAccess\RepositoryBase.cs:行号 16
   在 FileService.DataAccess.AttachmentDa.GetDeleteAttachments() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.DataAccess\AttachmentDa.cs:行号 24
   在 FileService.Biz.AttachmentBiz.DeleteAttachment() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.Biz\AttachmentBiz.cs:行号 20
   在 FileService.WebApi.Jobs.DeleteAttachmentJob.<>c.<Execute>b__1_0() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.WebApi\Jobs\DeleteAttachmentJob.cs:行号 18
   在 System.Threading.Tasks.Task.Execute()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   在 FileService.WebApi.Jobs.DeleteAttachmentJob.<Execute>d__1.MoveNext() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.WebApi\Jobs\DeleteAttachmentJob.cs:行号 15
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Quartz.Core.JobRunShell.<Run>d__9.MoveNext()
   --- 内部异常堆栈跟踪的结尾 --- [See nested exception: System.Data.SqlClient.SqlException (0x80131904): 在与 SQL Server 建立连接时出现与网络相关的或特定于实例的错误。未找到或无法访问服务器。请验证实例名称是否正确并且 SQL Server 已配置为允许远程连接。 (provider: Named Pipes Provider, error: 40 - 无法打开到 SQL Server 的连接) ---> System.ComponentModel.Win32Exception (0x80004005): 找不到网络路径。
   在 System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling)
   在 System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   在 System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   在 System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   在 System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   在 System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.Open()
   在 FileService.DataAccess.RepositoryBase.Db[T](Func`2 func) 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.DataAccess\RepositoryBase.cs:行号 16
   在 FileService.DataAccess.AttachmentDa.GetDeleteAttachments() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.DataAccess\AttachmentDa.cs:行号 24
   在 FileService.Biz.AttachmentBiz.DeleteAttachment() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.Biz\AttachmentBiz.cs:行号 20
   在 FileService.WebApi.Jobs.DeleteAttachmentJob.<>c.<Execute>b__1_0() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.WebApi\Jobs\DeleteAttachmentJob.cs:行号 18
   在 System.Threading.Tasks.Task.Execute()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   在 FileService.WebApi.Jobs.DeleteAttachmentJob.<Execute>d__1.MoveNext() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.WebApi\Jobs\DeleteAttachmentJob.cs:行号 15
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Quartz.Core.JobRunShell.<Run>d__9.MoveNext()
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:53,State:0,Class:20]


[2017-09-29 09:36:18,739]  15 -- DEBUG -- Debuglog [Debug] -- 类名:[QuartzLogProvider]; 方法:[<GetLogger>b__5_0];
[9:36:18] [Error] Job UnUsedAttachment.DeleteAttachment threw an exception. 

Quartz.SchedulerException: Job threw an unhandled exception. ---> System.InvalidOperationException: 超时时间已到。超时时间已到，但是尚未从池中获取连接。出现这种情况可能是因为所有池连接均在使用，并且达到了最大池大小。
   在 System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   在 System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.Open()
   在 FileService.DataAccess.RepositoryBase.Db[T](Func`2 func) 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.DataAccess\RepositoryBase.cs:行号 16
   在 FileService.DataAccess.AttachmentDa.GetDeleteAttachments() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.DataAccess\AttachmentDa.cs:行号 24
   在 FileService.Biz.AttachmentBiz.DeleteAttachment() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.Biz\AttachmentBiz.cs:行号 20
   在 FileService.WebApi.Jobs.DeleteAttachmentJob.<>c.<Execute>b__1_0() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.WebApi\Jobs\DeleteAttachmentJob.cs:行号 18
   在 System.Threading.Tasks.Task.Execute()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   在 FileService.WebApi.Jobs.DeleteAttachmentJob.<Execute>d__1.MoveNext() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.WebApi\Jobs\DeleteAttachmentJob.cs:行号 15
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Quartz.Core.JobRunShell.<Run>d__9.MoveNext()
   --- 内部异常堆栈跟踪的结尾 --- [See nested exception: System.InvalidOperationException: 超时时间已到。超时时间已到，但是尚未从池中获取连接。出现这种情况可能是因为所有池连接均在使用，并且达到了最大池大小。
   在 System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   在 System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.Open()
   在 FileService.DataAccess.RepositoryBase.Db[T](Func`2 func) 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.DataAccess\RepositoryBase.cs:行号 16
   在 FileService.DataAccess.AttachmentDa.GetDeleteAttachments() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.DataAccess\AttachmentDa.cs:行号 24
   在 FileService.Biz.AttachmentBiz.DeleteAttachment() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.Biz\AttachmentBiz.cs:行号 20
   在 FileService.WebApi.Jobs.DeleteAttachmentJob.<>c.<Execute>b__1_0() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.WebApi\Jobs\DeleteAttachmentJob.cs:行号 18
   在 System.Threading.Tasks.Task.Execute()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   在 FileService.WebApi.Jobs.DeleteAttachmentJob.<Execute>d__1.MoveNext() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.WebApi\Jobs\DeleteAttachmentJob.cs:行号 15
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Quartz.Core.JobRunShell.<Run>d__9.MoveNext()]


[2017-09-29 09:36:18,770]  7 -- DEBUG -- Debuglog [Debug] -- 类名:[QuartzLogProvider]; 方法:[<GetLogger>b__5_0];
[9:36:18] [Error] Job UnUsedAttachment.DeleteAttachment threw an unhandled Exception:  

System.Data.SqlClient.SqlException (0x80131904): 在与 SQL Server 建立连接时出现与网络相关的或特定于实例的错误。未找到或无法访问服务器。请验证实例名称是否正确并且 SQL Server 已配置为允许远程连接。 (provider: Named Pipes Provider, error: 40 - 无法打开到 SQL Server 的连接) ---> System.ComponentModel.Win32Exception (0x80004005): 找不到网络路径。
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   在 System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.Open()
   在 FileService.DataAccess.RepositoryBase.Db[T](Func`2 func) 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.DataAccess\RepositoryBase.cs:行号 16
   在 FileService.DataAccess.AttachmentDa.GetDeleteAttachments() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.DataAccess\AttachmentDa.cs:行号 24
   在 FileService.Biz.AttachmentBiz.DeleteAttachment() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.Biz\AttachmentBiz.cs:行号 20
   在 FileService.WebApi.Jobs.DeleteAttachmentJob.<>c.<Execute>b__1_0() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.WebApi\Jobs\DeleteAttachmentJob.cs:行号 18
   在 System.Threading.Tasks.Task.Execute()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   在 FileService.WebApi.Jobs.DeleteAttachmentJob.<Execute>d__1.MoveNext() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.WebApi\Jobs\DeleteAttachmentJob.cs:行号 15
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Quartz.Core.JobRunShell.<Run>d__9.MoveNext()
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:53,State:0,Class:20


[2017-09-29 09:36:22,061]  7 -- DEBUG -- Debuglog [Debug] -- 类名:[QuartzLogProvider]; 方法:[<GetLogger>b__5_0];
[9:36:22] [Error] Job UnUsedAttachment.DeleteAttachment threw an exception. 

Quartz.SchedulerException: Job threw an unhandled exception. ---> System.Data.SqlClient.SqlException: 在与 SQL Server 建立连接时出现与网络相关的或特定于实例的错误。未找到或无法访问服务器。请验证实例名称是否正确并且 SQL Server 已配置为允许远程连接。 (provider: Named Pipes Provider, error: 40 - 无法打开到 SQL Server 的连接) ---> System.ComponentModel.Win32Exception: 找不到网络路径。
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   在 System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.Open()
   在 FileService.DataAccess.RepositoryBase.Db[T](Func`2 func) 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.DataAccess\RepositoryBase.cs:行号 16
   在 FileService.DataAccess.AttachmentDa.GetDeleteAttachments() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.DataAccess\AttachmentDa.cs:行号 24
   在 FileService.Biz.AttachmentBiz.DeleteAttachment() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.Biz\AttachmentBiz.cs:行号 20
   在 FileService.WebApi.Jobs.DeleteAttachmentJob.<>c.<Execute>b__1_0() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.WebApi\Jobs\DeleteAttachmentJob.cs:行号 18
   在 System.Threading.Tasks.Task.Execute()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   在 FileService.WebApi.Jobs.DeleteAttachmentJob.<Execute>d__1.MoveNext() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.WebApi\Jobs\DeleteAttachmentJob.cs:行号 15
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Quartz.Core.JobRunShell.<Run>d__9.MoveNext()
   --- 内部异常堆栈跟踪的结尾 --- [See nested exception: System.Data.SqlClient.SqlException (0x80131904): 在与 SQL Server 建立连接时出现与网络相关的或特定于实例的错误。未找到或无法访问服务器。请验证实例名称是否正确并且 SQL Server 已配置为允许远程连接。 (provider: Named Pipes Provider, error: 40 - 无法打开到 SQL Server 的连接) ---> System.ComponentModel.Win32Exception (0x80004005): 找不到网络路径。
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   在 System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.Open()
   在 FileService.DataAccess.RepositoryBase.Db[T](Func`2 func) 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.DataAccess\RepositoryBase.cs:行号 16
   在 FileService.DataAccess.AttachmentDa.GetDeleteAttachments() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.DataAccess\AttachmentDa.cs:行号 24
   在 FileService.Biz.AttachmentBiz.DeleteAttachment() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.Biz\AttachmentBiz.cs:行号 20
   在 FileService.WebApi.Jobs.DeleteAttachmentJob.<>c.<Execute>b__1_0() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.WebApi\Jobs\DeleteAttachmentJob.cs:行号 18
   在 System.Threading.Tasks.Task.Execute()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   在 FileService.WebApi.Jobs.DeleteAttachmentJob.<Execute>d__1.MoveNext() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.WebApi\Jobs\DeleteAttachmentJob.cs:行号 15
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Quartz.Core.JobRunShell.<Run>d__9.MoveNext()
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:53,State:0,Class:20]


[2017-09-29 09:36:22,061]  9 -- DEBUG -- Debuglog [Debug] -- 类名:[QuartzLogProvider]; 方法:[<GetLogger>b__5_0];
[9:36:22] [Error] Job UnUsedAttachment.DeleteAttachment threw an unhandled Exception:  

System.Data.SqlClient.SqlException (0x80131904): 在与 SQL Server 建立连接时出现与网络相关的或特定于实例的错误。未找到或无法访问服务器。请验证实例名称是否正确并且 SQL Server 已配置为允许远程连接。 (provider: Named Pipes Provider, error: 40 - 无法打开到 SQL Server 的连接) ---> System.ComponentModel.Win32Exception (0x80004005): 找不到网络路径。
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   在 System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.Open()
   在 FileService.DataAccess.RepositoryBase.Db[T](Func`2 func) 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.DataAccess\RepositoryBase.cs:行号 16
   在 FileService.DataAccess.AttachmentDa.GetDeleteAttachments() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.DataAccess\AttachmentDa.cs:行号 24
   在 FileService.Biz.AttachmentBiz.DeleteAttachment() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.Biz\AttachmentBiz.cs:行号 20
   在 FileService.WebApi.Jobs.DeleteAttachmentJob.<>c.<Execute>b__1_0() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.WebApi\Jobs\DeleteAttachmentJob.cs:行号 18
   在 System.Threading.Tasks.Task.Execute()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   在 FileService.WebApi.Jobs.DeleteAttachmentJob.<Execute>d__1.MoveNext() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.WebApi\Jobs\DeleteAttachmentJob.cs:行号 15
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Quartz.Core.JobRunShell.<Run>d__9.MoveNext()
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:53,State:0,Class:20


[2017-09-29 09:36:22,077]  9 -- DEBUG -- Debuglog [Debug] -- 类名:[QuartzLogProvider]; 方法:[<GetLogger>b__5_0];
[9:36:22] [Error] Job UnUsedAttachment.DeleteAttachment threw an exception. 

Quartz.SchedulerException: Job threw an unhandled exception. ---> System.Data.SqlClient.SqlException: 在与 SQL Server 建立连接时出现与网络相关的或特定于实例的错误。未找到或无法访问服务器。请验证实例名称是否正确并且 SQL Server 已配置为允许远程连接。 (provider: Named Pipes Provider, error: 40 - 无法打开到 SQL Server 的连接) ---> System.ComponentModel.Win32Exception: 找不到网络路径。
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   在 System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.Open()
   在 FileService.DataAccess.RepositoryBase.Db[T](Func`2 func) 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.DataAccess\RepositoryBase.cs:行号 16
   在 FileService.DataAccess.AttachmentDa.GetDeleteAttachments() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.DataAccess\AttachmentDa.cs:行号 24
   在 FileService.Biz.AttachmentBiz.DeleteAttachment() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.Biz\AttachmentBiz.cs:行号 20
   在 FileService.WebApi.Jobs.DeleteAttachmentJob.<>c.<Execute>b__1_0() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.WebApi\Jobs\DeleteAttachmentJob.cs:行号 18
   在 System.Threading.Tasks.Task.Execute()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   在 FileService.WebApi.Jobs.DeleteAttachmentJob.<Execute>d__1.MoveNext() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.WebApi\Jobs\DeleteAttachmentJob.cs:行号 15
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Quartz.Core.JobRunShell.<Run>d__9.MoveNext()
   --- 内部异常堆栈跟踪的结尾 --- [See nested exception: System.Data.SqlClient.SqlException (0x80131904): 在与 SQL Server 建立连接时出现与网络相关的或特定于实例的错误。未找到或无法访问服务器。请验证实例名称是否正确并且 SQL Server 已配置为允许远程连接。 (provider: Named Pipes Provider, error: 40 - 无法打开到 SQL Server 的连接) ---> System.ComponentModel.Win32Exception (0x80004005): 找不到网络路径。
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   在 System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.Open()
   在 FileService.DataAccess.RepositoryBase.Db[T](Func`2 func) 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.DataAccess\RepositoryBase.cs:行号 16
   在 FileService.DataAccess.AttachmentDa.GetDeleteAttachments() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.DataAccess\AttachmentDa.cs:行号 24
   在 FileService.Biz.AttachmentBiz.DeleteAttachment() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.Biz\AttachmentBiz.cs:行号 20
   在 FileService.WebApi.Jobs.DeleteAttachmentJob.<>c.<Execute>b__1_0() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.WebApi\Jobs\DeleteAttachmentJob.cs:行号 18
   在 System.Threading.Tasks.Task.Execute()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   在 FileService.WebApi.Jobs.DeleteAttachmentJob.<Execute>d__1.MoveNext() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.WebApi\Jobs\DeleteAttachmentJob.cs:行号 15
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Quartz.Core.JobRunShell.<Run>d__9.MoveNext()
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:53,State:0,Class:20]


[2017-09-29 09:38:06,514]  9 -- DEBUG -- Debuglog [Debug] -- 类名:[QuartzLogProvider]; 方法:[<GetLogger>b__5_0];
[9:38:06] [Error] Job UnUsedAttachment.DeleteAttachment threw an unhandled Exception:  

System.Data.SqlClient.SqlException (0x80131904): 连接超时时间已到。在尝试使用预登录握手确认时超过了此超时时间。这可能是因为预登录握手失败或服务器未能及时响应。  尝试连接到此服务器时花费的持续时间是 - [Pre-Login] initialization=2611；handshake=1678； ---> System.ComponentModel.Win32Exception (0x80004005): 等待的操作过时。
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   在 System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.Open()
   在 FileService.DataAccess.RepositoryBase.Db[T](Func`2 func) 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.DataAccess\RepositoryBase.cs:行号 16
   在 FileService.DataAccess.AttachmentDa.DeleteAttachments(List`1 attachmentIds) 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.DataAccess\AttachmentDa.cs:行号 34
   在 FileService.Biz.AttachmentBiz.DeleteAttachment() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.Biz\AttachmentBiz.cs:行号 35
   在 FileService.WebApi.Jobs.DeleteAttachmentJob.<>c.<Execute>b__1_0() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.WebApi\Jobs\DeleteAttachmentJob.cs:行号 18
   在 System.Threading.Tasks.Task.Execute()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   在 FileService.WebApi.Jobs.DeleteAttachmentJob.<Execute>d__1.MoveNext() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.WebApi\Jobs\DeleteAttachmentJob.cs:行号 15
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Quartz.Core.JobRunShell.<Run>d__9.MoveNext()
ClientConnectionId:e80b3f92-6e23-47fd-98ca-b9a646836214
Error Number:-2,State:0,Class:11


[2017-09-29 09:38:06,514]  9 -- DEBUG -- Debuglog [Debug] -- 类名:[QuartzLogProvider]; 方法:[<GetLogger>b__5_0];
[9:38:06] [Error] Job UnUsedAttachment.DeleteAttachment threw an exception. 

Quartz.SchedulerException: Job threw an unhandled exception. ---> System.Data.SqlClient.SqlException: 连接超时时间已到。在尝试使用预登录握手确认时超过了此超时时间。这可能是因为预登录握手失败或服务器未能及时响应。  尝试连接到此服务器时花费的持续时间是 - [Pre-Login] initialization=2611；handshake=1678； ---> System.ComponentModel.Win32Exception: 等待的操作过时。
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   在 System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.Open()
   在 FileService.DataAccess.RepositoryBase.Db[T](Func`2 func) 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.DataAccess\RepositoryBase.cs:行号 16
   在 FileService.DataAccess.AttachmentDa.DeleteAttachments(List`1 attachmentIds) 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.DataAccess\AttachmentDa.cs:行号 34
   在 FileService.Biz.AttachmentBiz.DeleteAttachment() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.Biz\AttachmentBiz.cs:行号 35
   在 FileService.WebApi.Jobs.DeleteAttachmentJob.<>c.<Execute>b__1_0() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.WebApi\Jobs\DeleteAttachmentJob.cs:行号 18
   在 System.Threading.Tasks.Task.Execute()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   在 FileService.WebApi.Jobs.DeleteAttachmentJob.<Execute>d__1.MoveNext() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.WebApi\Jobs\DeleteAttachmentJob.cs:行号 15
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Quartz.Core.JobRunShell.<Run>d__9.MoveNext()
   --- 内部异常堆栈跟踪的结尾 --- [See nested exception: System.Data.SqlClient.SqlException (0x80131904): 连接超时时间已到。在尝试使用预登录握手确认时超过了此超时时间。这可能是因为预登录握手失败或服务器未能及时响应。  尝试连接到此服务器时花费的持续时间是 - [Pre-Login] initialization=2611；handshake=1678； ---> System.ComponentModel.Win32Exception (0x80004005): 等待的操作过时。
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   在 System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.Open()
   在 FileService.DataAccess.RepositoryBase.Db[T](Func`2 func) 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.DataAccess\RepositoryBase.cs:行号 16
   在 FileService.DataAccess.AttachmentDa.DeleteAttachments(List`1 attachmentIds) 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.DataAccess\AttachmentDa.cs:行号 34
   在 FileService.Biz.AttachmentBiz.DeleteAttachment() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.Biz\AttachmentBiz.cs:行号 35
   在 FileService.WebApi.Jobs.DeleteAttachmentJob.<>c.<Execute>b__1_0() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.WebApi\Jobs\DeleteAttachmentJob.cs:行号 18
   在 System.Threading.Tasks.Task.Execute()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   在 FileService.WebApi.Jobs.DeleteAttachmentJob.<Execute>d__1.MoveNext() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.WebApi\Jobs\DeleteAttachmentJob.cs:行号 15
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Quartz.Core.JobRunShell.<Run>d__9.MoveNext()
ClientConnectionId:e80b3f92-6e23-47fd-98ca-b9a646836214
Error Number:-2,State:0,Class:11]


[2017-09-29 09:38:06,514]  8 -- DEBUG -- Debuglog [Debug] -- 类名:[QuartzLogProvider]; 方法:[<GetLogger>b__5_0];
[9:38:06] [Error] Job UnUsedAttachment.DeleteAttachment threw an unhandled Exception:  

System.Data.SqlClient.SqlException (0x80131904): 连接超时时间已到。在尝试使用预登录握手确认时超过了此超时时间。这可能是因为预登录握手失败或服务器未能及时响应。  尝试连接到此服务器时花费的持续时间是 - [Pre-Login] initialization=2611；handshake=1678； ---> System.ComponentModel.Win32Exception (0x80004005): 等待的操作过时。
   在 System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling)
   在 System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   在 System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   在 System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   在 System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   在 System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.Open()
   在 FileService.DataAccess.RepositoryBase.Db[T](Func`2 func) 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.DataAccess\RepositoryBase.cs:行号 16
   在 FileService.DataAccess.AttachmentDa.GetDeleteAttachments() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.DataAccess\AttachmentDa.cs:行号 24
   在 FileService.Biz.AttachmentBiz.DeleteAttachment() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.Biz\AttachmentBiz.cs:行号 20
   在 FileService.WebApi.Jobs.DeleteAttachmentJob.<>c.<Execute>b__1_0() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.WebApi\Jobs\DeleteAttachmentJob.cs:行号 18
   在 System.Threading.Tasks.Task.Execute()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   在 FileService.WebApi.Jobs.DeleteAttachmentJob.<Execute>d__1.MoveNext() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.WebApi\Jobs\DeleteAttachmentJob.cs:行号 15
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Quartz.Core.JobRunShell.<Run>d__9.MoveNext()
ClientConnectionId:e80b3f92-6e23-47fd-98ca-b9a646836214
Error Number:-2,State:0,Class:11


[2017-09-29 09:38:06,514]  8 -- DEBUG -- Debuglog [Debug] -- 类名:[QuartzLogProvider]; 方法:[<GetLogger>b__5_0];
[9:38:06] [Error] Job UnUsedAttachment.DeleteAttachment threw an exception. 

Quartz.SchedulerException: Job threw an unhandled exception. ---> System.Data.SqlClient.SqlException: 连接超时时间已到。在尝试使用预登录握手确认时超过了此超时时间。这可能是因为预登录握手失败或服务器未能及时响应。  尝试连接到此服务器时花费的持续时间是 - [Pre-Login] initialization=2611；handshake=1678； ---> System.ComponentModel.Win32Exception: 等待的操作过时。
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling)
   在 System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   在 System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   在 System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   在 System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   在 System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.Open()
   在 FileService.DataAccess.RepositoryBase.Db[T](Func`2 func) 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.DataAccess\RepositoryBase.cs:行号 16
   在 FileService.DataAccess.AttachmentDa.GetDeleteAttachments() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.DataAccess\AttachmentDa.cs:行号 24
   在 FileService.Biz.AttachmentBiz.DeleteAttachment() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.Biz\AttachmentBiz.cs:行号 20
   在 FileService.WebApi.Jobs.DeleteAttachmentJob.<>c.<Execute>b__1_0() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.WebApi\Jobs\DeleteAttachmentJob.cs:行号 18
   在 System.Threading.Tasks.Task.Execute()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   在 FileService.WebApi.Jobs.DeleteAttachmentJob.<Execute>d__1.MoveNext() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.WebApi\Jobs\DeleteAttachmentJob.cs:行号 15
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Quartz.Core.JobRunShell.<Run>d__9.MoveNext()
   --- 内部异常堆栈跟踪的结尾 --- [See nested exception: System.Data.SqlClient.SqlException (0x80131904): 连接超时时间已到。在尝试使用预登录握手确认时超过了此超时时间。这可能是因为预登录握手失败或服务器未能及时响应。  尝试连接到此服务器时花费的持续时间是 - [Pre-Login] initialization=2611；handshake=1678； ---> System.ComponentModel.Win32Exception (0x80004005): 等待的操作过时。
   在 System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling)
   在 System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   在 System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   在 System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   在 System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   在 System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.Open()
   在 FileService.DataAccess.RepositoryBase.Db[T](Func`2 func) 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.DataAccess\RepositoryBase.cs:行号 16
   在 FileService.DataAccess.AttachmentDa.GetDeleteAttachments() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.DataAccess\AttachmentDa.cs:行号 24
   在 FileService.Biz.AttachmentBiz.DeleteAttachment() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.Biz\AttachmentBiz.cs:行号 20
   在 FileService.WebApi.Jobs.DeleteAttachmentJob.<>c.<Execute>b__1_0() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.WebApi\Jobs\DeleteAttachmentJob.cs:行号 18
   在 System.Threading.Tasks.Task.Execute()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   在 FileService.WebApi.Jobs.DeleteAttachmentJob.<Execute>d__1.MoveNext() 位置 E:\Ourtm\04开发资料\our.tm_Pro_v2\FileService\FileService.WebApi\Jobs\DeleteAttachmentJob.cs:行号 15
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Quartz.Core.JobRunShell.<Run>d__9.MoveNext()
ClientConnectionId:e80b3f92-6e23-47fd-98ca-b9a646836214
Error Number:-2,State:0,Class:11]
